spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
  application:
    name: web-all
server:
  port: 8300
# feign超时
feign:
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000
