server:
  port: 8208

#mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.128:3306/gmall_user?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
  redis:
    host: 192.168.200.128
    port: 6379
# feign超时
feign:
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml    #扫描mapper文件的路径
  configuration:
    map-underscore-to-camel-case: true      #开启驼峰命名转换
