server:
  port: 8080

#mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.128:3306/gmall_product?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  application:
    name: service-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
  redis:
    host: 192.168.200.128
    port: 6379

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml    #扫描mapper文件的路径
  configuration:
    map-underscore-to-camel-case: true      #开启驼峰命名转换
