server:
  port: 9203
spring:
  application:
    name: service-list
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
  elasticsearch:
    rest:
      uris: 192.168.200.128:9200
  redis:
    port: 6379
    host: 192.168.200.128

# feign超时
feign:
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000
